# -*- coding: utf-8 -*-
"""House Pricing Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_IUhgv01z-ItldUNxv75nsR084q-ZTS
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from google.colab import drive

drive.mount('/content/drive')

# Load datasets
train_df = pd.read_csv('drive/MyDrive/ML/train.csv')
test_df = pd.read_csv('drive/MyDrive/ML/test.csv')

# Prepare data
X_train = train_df.drop(columns=['ID', 'medv'])
y_train = train_df['medv']
X_test = test_df.drop(columns=['ID'])

# Split data
X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Train model
model = LinearRegression()
model.fit(X_train_split, y_train_split)

# Validate model
y_val_pred = model.predict(X_val_split)
mse = mean_squared_error(y_val_split, y_val_pred)
print(f"Mean Squared Error: {mse}")

# Make predictions
test_predictions = model.predict(X_test)

# Save predictions
test_df['predictions'] = test_predictions
test_df.to_csv('drive/MyDrive/ML/test_predictions.csv', index=False)